apiVersion: v1
kind: Secret
metadata:
  name: MS-Secret
type: Opaque
data:
  NODE_ENV: ZGV2
  MERCADOPAGO_ACCESS_TOKEN: QVBQX1VTUi02ODQ3ODE4ODE2NzQ1MjI3LTA1MjcxNy0xYjk4MzIxNmYyOGIzZjk1YTk5Y2QwYmJkZmQ0ODdmYy0yNzkxMzQ1MDc=